call npm run scss-main
call npm run scss-blue
call npm run scss-darkblue
call npm run scss-gray
call npm run scss-green
call npm run scss-greenish
call npm run scss-lightblue
call npm run scss-purple
call npm run scss-red
call npm run scss-redish
call npm run scss-turqoise
call npm run scss-orange